### ISSUE TITLE
PID Control requires a time interval

### ISSUE THREAD

**Issue by QuickC** [ms-iot/pid-controller#2]
I applaud the effort, but a PID controller must have the time interval for updates locked in order to work or even be tunable.   Right now the control system is dependent on the rate at which the control variables get method is called.  note also that the Integral accumulator must be capped to a max value, and disabled if the velocity can be set to zero.

**Comment by wind-rider** [comment]
Good point - I think the developers now assumed that `ControlVariable` would be read in fixed intervals.

To make it dependent on a variable time interval, the `ControlVariable` property could be converted to a function with one parameter:
```
public float ControlVariable(TimeSpan timeSinceLastUpdate)
{
...
}
```

As far as I understand, the time that passed only influences the Integral and Derivative action.

The `IntegralTerm` calculation would then be updated to:
```
IntegralTerm += (GainIntegral * error * timeSinceLastUpdate.Milliseconds);
```

The `derivativeTerm ` calculation would then be updated to:
```
float dInput = processVariable - ProcessVariableLast;
float derivativeTerm = -GainDerivative * (dInput / timeSinceLastUpdate.Milliseconds);
```

I'm not sure why the original author used a (-) in front of the Derivative action (see https://github.com/ms-iot/pid-controller/blob/34c0926df7d7d21fd8db9723b9532abc0dea15a5/PidController/PidController/PidController.cs#L38); I would say that it is better to use a (+) there and compensate for it in the tuning of `GainDerivative ` so that it is closer to the [block diagram of the PID controller](https://en.wikipedia.org/wiki/PID_controller#/media/File:PID_en.svg) on Wikipedia

What do you think?

One side note: when a timestep parameter is added, the projects using this library will also need to update their code...

**Comment by ooeygui** [comment]
I believe this was completed by @wind-rider. Thank you!
